package task5.views;

interface MenuConstants {
    String ALL_RECORDS = "ALL_RECORDS";
    String REQUEST_SURNAME = "REQUEST_SURNAME";
    String REQUEST_NAME = "REQUEST_NAME";
    String REQUEST_BIRTH_DATE = "REQUEST_BIRTH_DATE";
    String REQUEST_PHONE= "REQUEST_PHONE";
    String REQUEST_ADDRESS= "REQUEST_ADDRESS";
    String INVALID_INPUT= "INVALID_INPUT";
    String SURNAME_PATTERN= "SURNAME_PATTERN";
    String NAME_PATTERN= "NAME_PATTERN";
    String BIRTH_DAY_PATTERN= "BIRTH_DAY_PATTERN";
    String PHONE_PATTERN= "PHONE_PATTERN";
    String ADDRESS_PATTERN= "ADDRESS_PATTERN";
    String OPTION_1= "OPTION_1";
    String OPTION_2= "OPTION_2";
    String EXIT_OPTION= "EXIT_OPTION";
    String CHANGE_LANGUAGE_OPTION = "CHANGE_LANGUAGE_OPTION";
    String MAIN_MENU_REQUEST = "MAIN_MENU_REQUEST";
    String MAIN_MENU_PATTERN = "MAIN_MENU_PATTERN";

}
